services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: evanfy
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: evanfy-nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx-logs:/var/log/nginx
    depends_on:
      - nextjs
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs: